# fly.toml app configuration file generated for runeportal on 2024-01-20T21:02:57-03:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "runeportal"
primary_region = "ewr"

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
