/** @format */

export const bosses = [
  { id: 17, name: "Abyssal Sire" },
  { id: 18, name: "Alchemical Hydra" },
  { id: 19, name: "Artio" },
  { id: 20, name: "Barrows Chests" },
  { id: 21, name: "Bryophyta" },
  { id: 22, name: "Callisto" },
  { id: 23, name: "Cal'varion" },
  { id: 24, name: "Cerberus" },
  { id: 25, name: "Chambers of Xeric" },
  { id: 26, name: "Chambers of Xeric: Challenge Mode" },
  { id: 27, name: "Chaos Elemental" },
  { id: 28, name: "Chaos Fanatic" },
  { id: 29, name: "Commander Zilyana" },
  { id: 30, name: "Corporeal Beast" },
  { id: 31, name: "Crazy Archaeologist" },
  { id: 32, name: "Dagannoth Prime" },
  { id: 33, name: "Dagannoth Rex" },
  { id: 34, name: "Dagannoth Supreme" },
  { id: 35, name: "Deranged Archaeologist" },
  { id: 36, name: "Duke Sucellus" },
  { id: 37, name: "General Graardor" },
  { id: 38, name: "Giant Mole" },
  { id: 39, name: "Grotesque Guardians" },
  { id: 40, name: "Hespori" },
  { id: 41, name: "Kalphite Queen" },
  { id: 42, name: "King Black Dragon" },
  { id: 43, name: "Kraken" },
  { id: 44, name: "Kree'Arra" },
  { id: 45, name: "K'ril Tsutsaroth" },
  { id: 46, name: "Mimic" },
  { id: 47, name: "Nex" },
  { id: 48, name: "Nightmare" },
  { id: 49, name: "Phosani's Nightmare" },
  { id: 50, name: "Obor" },
  { id: 51, name: "Phantom Muspah" },
  { id: 52, name: "Sarachnis" },
  { id: 53, name: "Scorpia" },
  { id: 54, name: "Scurrius" },
  { id: 55, name: "Skotizo" },
  { id: 56, name: "Spindel" },
  { id: 57, name: "Tempoross" },
  { id: 58, name: "The Gauntlet" },
  { id: 59, name: "The Corrupted Gauntlet" },
  { id: 60, name: "The Leviathan" },
  { id: 61, name: "The Whisperer" },
  { id: 62, name: "Theatre of Blood" },
  { id: 63, name: "Theatre of Blood: Hard Mode" },
  { id: 64, name: "Thermonuclear Smoke Devil" },
  { id: 65, name: "Tombs of Amascut" },
  { id: 66, name: "Tombs of Amascut: Expert Mode" },
  { id: 67, name: "TzKal-Zuk" },
  { id: 68, name: "TzTok-Jad" },
  { id: 69, name: "Vardorvis" },
  { id: 70, name: "Venenatis" },
  { id: 71, name: "Vet'ion" },
  { id: 72, name: "Vorkath" },
  { id: 73, name: "Wintertodt" },
  { id: 74, name: "Zalcano" },
  { id: 75, name: "Zulrah" },
];

export const clueScrolls = [
  { id: 6, name: "Clue Scrolls (all)" },
  { id: 7, name: "Clue Scrolls (beginner)" },
  { id: 8, name: "Clue Scrolls (easy)" },
  { id: 9, name: "Clue Scrolls (medium)" },
  { id: 10, name: "Clue Scrolls (hard)" },
  { id: 11, name: "Clue Scrolls (elite)" },
  { id: 12, name: "Clue Scrolls (master)" },
];

export const miniGames = [
  { id: 0, name: "League Points" },
  { id: 1, name: "Deadman Points" },
  { id: 2, name: "Bounty Hunter - Hunter" },
  { id: 3, name: "Bounty Hunter - Rogue" },
  { id: 4, name: "Bounty Hunter (Legacy) - Hunter" },
  { id: 5, name: "Bounty Hunter (Legacy) - Rogue" },
  { id: 13, name: "LMS - Rank" },
  { id: 14, name: "Soul Wars Zeal" },
  { id: 15, name: "Soul Wars Zeal" },
  { id: 16, name: "Rifts closed" },
];

export const skills = [
  "Overall",
  "Attack",
  "Defence",
  "Strength",
  "Hitpoints",
  "Ranged",
  "Prayer",
  "Magic",
  "Cooking",
  "Woodcutting",
  "Fletching",
  "Fishing",
  "Firemaking",
  "Crafting",
  "Smithing",
  "Mining",
  "Herblore",
  "Agility",
  "Thieving",
  "Slayer",
  "Farming",
  "Runecraft",
  "Hunter",
  "Construction",
];
